import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";

export default function Home() {
  const onClickHandlerBannerBtn = (e)=>{
    console.log('i got clicked', e)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Nearby Coffee</h1>

      <Banner bannerBtnText='View stores nearby' onClickHandlerBannerBtn={onClickHandlerBannerBtn} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
